# This file configures the hello-world app which serves public web traffic.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-products
spec:
  replicas: 1
  selector:
    matchLabels:
      app: products
  template:
    metadata:
      labels:
        app: products
    spec:
      containers:
      - name: products-app
        # Replace $GCLOUD_PROJECT with your project ID
        image: gcr.io/carepet-299416/microservice-products:latest
        # This app listens on port 5000 for web traffic by default.
        ports:
        - containerPort: 5000
        env:
          - name: PORT
            value: "5000"