# build: <path-of-Dockerfile>
# image: <name-image-dockerhub>

version: "3"
services:
  data_extraction:
    container_name: data-extraction
    image: data-extraction-image
    ports:
      - "5000:5000"
    build:
      context: ./
      dockerfile: Dockerfile
